
drop FUNCTION dbo.FN_FloatToString
GO
CREATE FUNCTION dbo.FN_FloatToString
	(
	@num	SQL_VARIANT
	)
RETURNS VARCHAR(20)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @rtnValue	VARCHAR(20)

	IF @num IS NULL
		SET @rtnValue=''
	ELSE IF @num=CONVERT(INTEGER,@num) OR 
			CONVERT(FLOAT,@num)=ROUND(CONVERT(FLOAT,@num),0) OR 
			CONVERT(FLOAT,@num)=CONVERT(INTEGER,@num)
		SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(INTEGER,@num))
	ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(FLOAT,@num),1) 
		SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,1),@num))
	ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(FLOAT,@num),2) 
		SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,2),@num))
	ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(FLOAT,@num),3) 
		SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,3),@num))
	ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(FLOAT,@num),4) 
		SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,4),@num))
	ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(FLOAT,@num),5) 
		SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,5),@num))
	ELSE
	BEGIN
		IF CONVERT(FLOAT,@num)=ROUND(CONVERT(DECIMAL(20,1),@num),1) 
			SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,1),@num))
		ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(DECIMAL(20,2),@num),2) 
			SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,2),@num))
		ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(DECIMAL(20,3),@num),3) 
			SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,3),@num))
		ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(DECIMAL(20,4),@num),4) 
			SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,4),@num))
		ELSE IF CONVERT(FLOAT,@num)=ROUND(CONVERT(DECIMAL(20,5),@num),5) 
			SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,5),@num))
		ELSE
			SET @rtnValue=CONVERT(VARCHAR(20),CONVERT(DECIMAL(20,6),@num))
	END
	RETURN(@rtnValue)
END

