if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[SP_GetBilNO]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[SP_GetBilNO]

--exec SP_GetBilNO 'BOM','2012-06-01',''

GO 
create PROCEDURE SP_GetBilNO(
	@BIL_ID VARCHAR(20),
	@DATE	DATETIME,
	@BIL_NO VARCHAR(20) OUTPUT
)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @BIL_PRE 	VARCHAR(10)
	DECLARE @DD_SET 	VARCHAR(10)
	DECLARE @SEQ_SET 	VARCHAR(10)
	DECLARE @DD_STR		VARCHAR(10)
	DECLARE @N 		INT
	
	SET @N = (SELECT COUNT(*) FROM TB_BILSET WHERE BIL_ID =@BIL_ID)
	IF @N = 1 
	BEGIN
		SET @DD_SET = (SELECT DD_SET FROM TB_BILSET WHERE BIL_ID =@BIL_ID)
		SET @BIL_PRE = (SELECT BIL_PRE FROM TB_BILSET WHERE BIL_ID =@BIL_ID)
		SET @SEQ_SET = (SELECT SEQ_SET FROM TB_BILSET WHERE BIL_ID =@BIL_ID)
		SET @DD_STR =  
			CASE @DD_SET
			WHEN 'YYYYMMDD' THEN CAST(YEAR(@DATE) AS VARCHAR(4))
					+ SUBSTRING('00',1,2-LEN(MONTH(@DATE))) + CAST(MONTH(@DATE) AS VARCHAR(2))
					+ SUBSTRING('00',1,2-LEN(DAY(@DATE))) + CAST(DAY(@DATE) AS VARCHAR(2))
			WHEN 'YYMMDD' THEN  SUBSTRING(CAST(YEAR(@DATE) AS VARCHAR(4)),3,2)
					+ SUBSTRING('00',1,2-LEN(MONTH(@DATE))) + CAST(MONTH(@DATE) AS VARCHAR(2))
					+ SUBSTRING('00',1,2-LEN(DAY(@DATE))) + CAST(DAY(@DATE) AS VARCHAR(2))
			WHEN 'YMMDD' THEN  SUBSTRING(CAST(YEAR(@DATE) AS VARCHAR(4)),4,1)
					+ SUBSTRING('00',1,2-LEN(MONTH(@DATE))) + CAST(MONTH(@DATE) AS VARCHAR(2))
					+ SUBSTRING('00',1,2-LEN(DAY(@DATE))) + CAST(DAY(@DATE) AS VARCHAR(2))
			WHEN 'YYYYMDD' THEN  CAST(YEAR(@DATE) AS VARCHAR(4))
					+ SUBSTRING('123456789ABCDEF',MONTH(@DATE),1)
					+ SUBSTRING('00',1,2-LEN(DAY(@DATE))) + CAST(DAY(@DATE) AS VARCHAR(2))
			WHEN 'YYMDD' THEN  SUBSTRING(CAST(YEAR(@DATE) AS VARCHAR(4)),3,2)
					+ SUBSTRING('123456789ABCDEF',MONTH(@DATE),1)
					+ SUBSTRING('00',1,2-LEN(DAY(@DATE))) + CAST(DAY(@DATE) AS VARCHAR(2))
			WHEN 'YYYYMM' THEN CAST(YEAR(@DATE) AS VARCHAR(4))
					+ SUBSTRING('00',1,2-LEN(MONTH(@DATE))) + CAST(MONTH(@DATE) AS VARCHAR(2))
			WHEN 'YYMM' THEN  SUBSTRING(CAST(YEAR(@DATE) AS VARCHAR(4)),3,2)
					+ SUBSTRING('00',1,2-LEN(MONTH(@DATE))) + CAST(MONTH(@DATE) AS VARCHAR(2))
			WHEN 'YYYYM' THEN  CAST(YEAR(@DATE) AS VARCHAR(4))
					+ SUBSTRING('123456789ABCDEF',MONTH(@DATE),1)
			WHEN 'YYM' THEN  SUBSTRING(CAST(YEAR(@DATE) AS VARCHAR(4)),3,2)
					+ SUBSTRING('123456789ABCDEF',MONTH(@DATE),1)
			ELSE ''
			END
		SET @N = 0
		SET @N = (SELECT ITM FROM TB_BILN WHERE BIL_SET = @BIL_PRE+@DD_STR And BIL_ID=@BIL_ID)
		IF ISNULL(@N,0)>0 
		BEGIN
			UPDATE TB_BILN SET ITM = @N+1 Where BIl_SET = @BIL_PRE+@DD_STR
			SET @BIL_NO =  @BIL_PRE+@DD_STR+ SUBSTRING('0000000000',1,LEN(@SEQ_SET)-LEN(CAST(@N+1 AS VARCHAR(10))))+ CAST(@N+1 AS VARCHAR(10))

		END
		ELSE
		BEGIN
			DELETE FROM TB_BILN WHERE BIL_SET = @BIL_PRE+@DD_STR
			INSERT INTO TB_BILN(BIL_ID,BIL_SET,ITM) VALUES(@BIL_ID,@BIL_PRE+@DD_STR,1)
			SET @BIL_NO =  @BIL_PRE+@DD_STR+ SUBSTRING('0000000000',1,LEN(@SEQ_SET)-1) + '1'
		END
	END
	ELSE
		RAISERROR('代码规则设置不正确！',16,1)

	SELECT @BIL_NO AS BIL_NO
END


